In [1]:
#Dependencies
import os
import csv
import pandas as pd
import numpy as np
from statistics import mean

In [2]:
#Store filepaths
lb_import = "Output/LBs_Fltr_Combine_Data.csv"
lb_df = pd.read_csv(lb_import)

In [4]:
#Create lists for the combine columns
height = []
weight = []
hands = []
arm = []
wonderlic = []
forty = []
bench = []
vert = []
broad = []
shuttle = []
three_cone = []
sixty_shuttle = []

#Place columns into independent rows
for index, row in lb_df.iterrows():
    height.append(row['Height\xa0(in)'])
    weight.append(row['Weight\xa0(lbs)'])
    hands.append(row['Hand Size\xa0(in)'])
    arm.append(row['Arm Length\xa0(in)'])
    wonderlic.append([row['Wonderlic']])
    forty.append(row['40\xa0Yard'])
    bench.append(row['Bench Press'])
    vert.append(row['Vert Leap\xa0(in)'])
    broad.append(row['Broad Jump\xa0(in)'])
    shuttle.append(row['Shuttle'])
    three_cone.append(row['3Cone'])
    sixty_shuttle.append(row['60Yd Shuttle'])

In [5]:
#Remove NaN values
hands = [x for x in hands if str(x) !='nan']
arm = [x for x in arm if str(x) !='nan']
wonderlic = [x for x in wonderlic if str(x) !='[nan]']
forty = [x for x in forty if str(x) !='nan']
bench = [x for x in bench if str(x) !='nan']
vert = [x for x in vert if str(x) !='nan']
broad = [x for x in broad if str(x) !='nan']
shuttle = [x for x in shuttle if str(x) !='nan']
three_cone = [x for x in three_cone if str(x) !='nan']
sixty_shuttle = [x for x in sixty_shuttle if str(x) !='nan']

In [15]:
sixty_shuttle

[11.9,
 10.93,
 11.91,
 11.15,
 11.1,
 11.43,
 11.46,
 12.51,
 11.52,
 11.39,
 11.97,
 11.89,
 11.23,
 11.41,
 11.4,
 12.11,
 11.85,
 11.59,
 11.76,
 11.91,
 11.56,
 11.27,
 11.26,
 11.61,
 11.43,
 11.89,
 11.89,
 12.08,
 11.56,
 11.94,
 11.84,
 11.44,
 11.93,
 11.78,
 11.56,
 12.31,
 11.45,
 12.58,
 11.65,
 11.79,
 11.77,
 11.73,
 11.68,
 11.65,
 11.42,
 11.85,
 11.6,
 11.51,
 11.94,
 11.93,
 11.51,
 11.44,
 11.97,
 11.62,
 11.22,
 11.78,
 11.41,
 12.2,
 11.68,
 11.41,
 11.5,
 11.96,
 12.5,
 11.57,
 11.48,
 11.62,
 11.2,
 11.5,
 11.33,
 11.55,
 12.26,
 11.44,
 12.07,
 11.8,
 11.15,
 11.5,
 11.63,
 11.49,
 11.84,
 11.97,
 11.49,
 11.66,
 11.89,
 11.61,
 12.27,
 12.19,
 11.74,
 11.84,
 11.46,
 11.59,
 11.41,
 11.99,
 11.77,
 11.08,
 11.21,
 11.91,
 11.51,
 11.73,
 11.84,
 11.65,
 11.7,
 11.23,
 11.74,
 12.09,
 11.05,
 11.31,
 12.81,
 11.35,
 11.35,
 12.08,
 11.7,
 11.32,
 11.67,
 11.29,
 11.01,
 12.01,
 11.87,
 11.62,
 11.42,
 11.12,
 11.6,
 11.49,
 11.96,
 11.97,
 12.4,
 11.91,
 12.8,
 11.58,
 11.93,
 11.05,
 12.39,
 10.88,
 11.16,
 11.6,
 11.11,
 11.56,
 12.06,
 11.38,
 11.81,
 11.73,
 11.99,
 11.85,
 11.73,
 10.95,
 12.05,
 12.12,
 11.75,
 11.65,
 12.39,
 11.5,
 11.5,
 10.98,
 11.57,
 11.75,
 12.36,
 11.17,
 11.79,
 11.2,
 11.71,
 11.71,
 11.15,
 11.47,
 12.12,
 11.42,
 11.51,
 11.76,
 12.16,
 11.81,
 11.95,
 12.11,
 11.38,
 11.75,
 11.73,
 12.12,
 12.22,
 12.14,
 11.9,
 11.28,
 11.3,
 11.23,
 11.64,
 12.0,
 12.21,
 11.97,
 11.43,
 11.95,
 11.78,
 11.97,
 12.2,
 11.87,
 11.68,
 11.43,
 11.78,
 11.69,
 11.51,
 11.79,
 11.67,
 11.32,
 12.18,
 11.34,
 11.65,
 11.53,
 11.64,
 11.58,
 11.5,
 11.52,
 11.73,
 11.5,
 11.77,
 11.52,
 12.02,
 11.88,
 11.28,
 11.87,
 11.82,
 11.31,
 12.48,
 10.96,
 11.35,
 12.1,
 12.08,
 11.58,
 11.85,
 11.65,
 11.47,
 11.94,
 11.63,
 12.15,
 11.33,
 11.81,
 11.06,
 11.78,
 11.76,
 11.66,
 11.43,
 11.3,
 11.69,
 12.18,
 11.72,
 11.46,
 11.63,
 11.4,
 11.6,
 12.08,
 11.56,
 12.56,
 11.93,
 12.06,
 11.99,
 11.46,
 11.74,
 12.27,
 12.38,
 12.06,
 11.96,
 12.56,
 12.18,
 11.26,
 11.9,
 12.64,
 11.68,
 11.36,
 11.27,
 11.26,
 12.14,
 11.93,
 12.14,
 11.87,
 12.53,
 11.82,
 11.95,
 12.03,
 12.41,
 11.65,
 11.85,
 11.6,
 11.83,
 12.04,
 12.23,
 12.16,
 11.77,
 12.4,
 11.89,
 11.95,
 12.3,
 11.76,
 11.77,
 12.3,
 11.5,
 12.02,
 11.34,
 12.25,
 11.06,
 11.37,
 12.4,
 12.58,
 11.72,
 12.18,
 11.9,
 12.34,
 12.15,
 12.22,
 11.68,
 11.94,
 11.88,
 11.51,
 11.25,
 12.44,
 12.08,
 12.26,
 11.95,
 12.31,
 11.78,
 11.91,
 11.37,
 12.09,
 11.45,
 12.45,
 13.05,
 12.04,
 11.99,
 12.21,
 11.95,
 11.89,
 12.03,
 12.46,
 12.07,
 11.61,
 12.78,
 12.2,
 12.22,
 11.86,
 11.5,
 11.75,
 12.91,
 12.21,
 12.03,
 12.11,
 12.11,
 12.06,
 13.38,
 12.35,
 11.49,
 11.86,
 11.94,
 12.03,
 11.4,
 12.36,
 12.17,
 11.88]

In [6]:
#Split lists into top 25 and bottom 25
#Wonderlic removed because not enough data
top_height = height[:25]
bottom_height = height[-25:]
top_weight = weight[:25]
bottom_weight = weight[-25:]
top_hands = hands[:25]
bottom_hands = hands[-25:]
top_arm = arm[:25]
bottom_arm = arm[-25:]
top_forty = forty[:25]
bottom_forty = forty[-25:]
top_bench = bench[:25]
bottom_bench = bench[-25:]
top_vert = vert[:25]
bottom_vert = vert[-25:]
top_broad = broad[:25]
bottom_broad = broad[-25:]
top_shuttle = shuttle[:25]
bottom_shuttle = shuttle[-25:]
top_three_cone = three_cone[:25]
bottom_three_cone = three_cone[-25:]
top_sixty_shuttle = sixty_shuttle[:25]
bottom_sixty_shuttle = sixty_shuttle[-25:]

In [7]:
#Calculate average of each list
#Top 25
top_height_avg = mean(top_height)
top_weight_avg = mean(top_weight)
top_hands_avg = mean(top_hands)
top_arm_avg = mean(top_arm)
top_forty_avg = mean(top_forty)
top_bench_avg = mean(top_bench)
top_vert_avg = mean(top_vert)
top_broad_avg = mean(top_broad)
top_shuttle_avg = mean(top_shuttle)
top_three_cone_avg = mean(top_three_cone)
top_sixty_shuttle_avg = mean(top_sixty_shuttle)

#Bottom 25
bottom_height_avg = mean(bottom_height)
bottom_weight_avg = mean(bottom_weight)
bottom_hands_avg = mean(bottom_hands)
bottom_arm_avg = mean(bottom_arm)
bottom_forty_avg = mean(bottom_forty)
bottom_bench_avg = mean(bottom_bench)
bottom_vert_avg = mean(bottom_vert)
bottom_broad_avg = mean(bottom_broad)
bottom_shuttle_avg = mean(bottom_shuttle)
bottom_three_cone_avg = mean(bottom_three_cone)
bottom_sixty_shuttle_avg = mean(bottom_sixty_shuttle)

#Overall
height_avg = mean(height)
weight_avg = mean(weight)
hands_avg = mean(hands)
arm_avg = mean(arm)
forty_avg = mean(forty)
bench_avg = mean(bench)
vert_avg = mean(vert)
broad_avg = mean(broad)
shuttle_avg = mean(shuttle)
three_cone_avg = mean(three_cone)
sixty_shuttle_avg = mean(sixty_shuttle)

In [8]:
#Create dictionary for column-oriented dataframe from the averages

averages = {'Category': ['Height (in)', 'Weight (lb)', 'Hand Size (in)', 'Arm Length (in)', '40 Yard', 'Bench Press',
                        'Vertical Leap (in)', 'Broad Jump (in)', 'Shuttle', '3 Cone Drill', '60 Yard Shuttle'],
            'Overall Avg.': [height_avg, weight_avg, hands_avg, arm_avg, forty_avg, bench_avg, vert_avg, broad_avg, shuttle_avg, 
                             three_cone_avg, sixty_shuttle_avg],
            'Top 25 Avg.': [top_height_avg, top_weight_avg, top_hands_avg, top_arm_avg, top_forty_avg, top_bench_avg,
                            top_vert_avg, top_broad_avg, top_shuttle_avg, top_three_cone_avg, top_sixty_shuttle_avg],
            'Bottom 25 Avg.': [bottom_height_avg, bottom_weight_avg, bottom_hands_avg, bottom_arm_avg, bottom_forty_avg, 
                               bottom_bench_avg, bottom_vert_avg, bottom_broad_avg, bottom_shuttle_avg, bottom_three_cone_avg,
                               bottom_sixty_shuttle_avg]}

In [9]:
#Create dataframe from dictionary
averages_df = pd.DataFrame.from_dict(averages)
averages_df

              Category  Overall Avg.  Top 25 Avg.  Bottom 25 Avg.
0          Height (in)     73.791818      73.5976         74.1160
1          Weight (lb)    238.362069     240.3200        232.9600
2       Hand Size (in)      9.503400       9.6516          9.4216
3      Arm Length (in)     32.241508      32.5568         32.2108
4              40 Yard      4.728853       4.6664          4.8540
5          Bench Press     21.495256      21.9200         18.0000
6   Vertical Leap (in)     33.651887      34.5600         31.1200
7      Broad Jump (in)    115.589015     117.0000        110.6400
8              Shuttle      4.296758       4.2212          4.4460
9         3 Cone Drill      7.193533       7.1540          7.2844
10     60 Yard Shuttle     11.778400      11.5820         12.1096

In [10]:
#Create function that calculates percent change
def pct_change(top, bottom):
    return (abs(top - bottom))/((top + bottom)/2) * 100

In [11]:
#Add new column with percent change
averages_df['Pct. Change(%)'] = pct_change(averages_df['Top 25 Avg.'], averages_df['Bottom 25 Avg.'])

In [12]:
#Calculate sum of pct. change column
total = averages_df['Pct. Change(%)'].sum()

#Created weighted percentage for each category, add to new column
averages_df['Weighted Pct.'] = (averages_df['Pct. Change(%)']/total)*100

In [13]:
averages_df

,Category,Overall Avg.,Top 25 Avg.,Bottom 25 Avg.,Pct. Change(%),Weighted Pct.
0,Height (in),73.791818,73.5976,74.1160,0.701899,1.202232
1,Weight (lb),238.362069,240.3200,232.9600,3.110210,5.327256
2,Hand Size (in),9.503400,9.6516,9.4216,2.411761,4.130933
3,Arm Length (in),32.241508,32.5568,32.2108,1.068435,1.830047
4,40 Yard,4.728853,4.6664,4.8540,3.941011,6.750276
5,Bench Press,21.495256,21.9200,18.0000,19.639279,33.638716
6,Vertical Leap (in),33.651887,34.5600,31.1200,10.475030,17.941931
7,Broad Jump (in),115.589015,117.0000,110.6400,5.587770,9.570892
8,Shuttle,4.296758,4.2212,4.4460,5.187373,8.885080
9,3 Cone Drill,7.193533,7.1540,7.2844,1.806294,3.093872
10,60 Yard Shuttle,11.778400,11.5820,12.1096,4.453899,7.628766

In [14]:
#Export to csv
export_csv = averages_df.to_csv('Output/LBs_Averages.csv', index=False, header=True)